name: openat

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [cc]
        include:
          - os: windows-latest
            cc: msvc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        ${{ matrix.cc }} openat.c
